core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('monitoring.urls', namespace='monitoring')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

monitoring/urls.py
from . import views
from django.urls import path
from django.conf.urls import handler404, handler400, handler403
from .views import CustomErrorView

app_name = 'monitoring'

handler400 = CustomErrorView.as_view()
handler403 = CustomErrorView.as_view()
handler404 = CustomErrorView.as_view()

urlpatterns = [
 path('', views.index, name='index'),
 path('<int:printer_id>', views.single_printer, name='printer'),
 path('reports', views.reports, name='reports'),
 path('report/<str:nm_report>/<str:qty_days>', views.single_report, name='report'),
 path('export_report/', views.export_report, name='export_report'),
 path('data-in-js/<str:nm_data>', views.data_in_js, name='data_in_js'),
 path('events', views.events, name='events'),
 path('forecast', views.forecast, name='forecast'),
]

templates/rab.html
{% for subnet in subnet_printer_count %}
<li>
    <a class="has-arrow" href="{% static 'javascript:void()' %}">
        <span class="nav-text">{{ subnet.area_name }}</span>
        <span class="badge badge-xs badge-light">{{ subnet.printer_count }}</span>
    </a>
    <ul aria-expanded="false">
        {% for stamp in unique_stamps %}
        {% if stamp.ip_address__subnet__name == subnet.name %}
        <li>
            <a class="has-arrow" href="{% static 'javascript:void()' %}">{{ stamp.model__stamp__name }}</a>
            <ul aria-expanded="false">
                {% for printer in printers %}
                {% if printer.model.stamp.name == stamp.model__stamp__name
                and printer.ip_address.subnet.name == subnet.name %}
                <li>
                    <a href={% url "monitoring:printer" printer.id %}>
                    {{ printer.model.name }} - {{ printer.location.cabinet.number }}/{{printer.location.department.name}}
                    </a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</li>
{% endfor %}

<!DOCTYPE html>
<head>
<!--Метаинформация о документе, ссылки на стили-->
</head>
<body>
<!--Основная часть документа-->
    <div id="preloader">
<!--Анимации загрузки-->
    </div>
    <div id="main-wrapper">
<!--Основной контейнер-->
        <div class="nav-header">
<!--Навигационное меню, для размешщения логотипа сайта в заголовке и переадресации на главную страницу-->
        </div>
        <div class="fixed-content-box">
<!--Боковая панель-->
        </div>
        <div class="header">
<!--Заголовок страницы-->
        </div>
        <div class="deznav">
<!-- Дополнительные элементы навигации в заголовке, для управления темой сайта и управления учетной записью-->
        </div>
        <div class="content-body">
<!--Основной контент страницы-->
        </div>
    </div>
    <script>
<!--Блок для размещения JavaScript-кода-->
    </script>
</body>


<table id="example" class="display" style="min-width: 1465px;">
    <thead>
<!--Заголовки таблицы-->
    </thead>
    <tbody>
    {% for printer_supply in printers_with_black_cart %}
    <tr>
        <td>
            <a href={% url "monitoring:printer" printer_supply.printer.id %}> {{ printer_supply.printer.model }}</a>
        </td>
        <td>{{ printer_supply.printer.ip_address }}</td>
        <td>{{ printer_supply.printer.get_is_active }}</td>
        <td>{{ printer_supply.printer.get_subnet_name }}</td>
        <td>{{ printer_supply.printer.location.cabinet.number }}</td>
        <td>{{ printer_supply.printer.location.department }}</td>
        <td>{{ printer_supply.remaining_supply_percentage }}</td>
    </tr>
    {% endfor %}
    </tbody>
    <tfoot>
<!--Подвал таблицы с заголовками-->
    </tfoot>
</table>

templates/template-errors.html
<!DOCTYPE html>
{% load static %}
<html lang="ru" class="h-100">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone=no">

	<title>{% block title %}{% endblock %}</title>

	<link rel="shortcut icon" type="image/png" href="{% static 'images/icon_net.png' %}" />

    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body class="h-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-5">
                    <div class="form-input-content text-center error-page">
                        {% block content %}
        	            {% endblock %}
						<div>
                            <a class="btn btn-primary" href="{% url 'monitoring:index' %}">Перейти на главную страницу</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="{% static 'vendor/global/global.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/custom.min.js' %}"></script>
<script src="{% static 'js/deznav-init.js' %}"></script>

</html>